services:
  backend-dev:
    build: .
    profiles: ["dev"]
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST_DEV}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME_DEV}
      DB_USERNAME: ${DB_USERNAME_DEV}
      DB_PASSWORD: ${BACK_USER_DEV_PASSWORD}
      JWT_SECRET: ${JWT_SECRET_DEV}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES:-20}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS:-30}
      JWT_REFRESH_GRACE_SECONDS: ${JWT_REFRESH_GRACE_SECONDS:-10}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS_DEV}
      SYSACAD_ENABLED: ${SYSACAD_ENABLED}
      SYSACAD_API_KEY: ${SYSACAD_API_KEY}
    networks:
      - app-network

  backend-test:
    build: .
    profiles: ["test"]
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: ${DB_HOST_TEST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME_TEST}
      DB_USERNAME: ${DB_USERNAME_TEST}
      DB_PASSWORD: ${BACK_USER_TEST_PASSWORD}
      JWT_SECRET: ${JWT_SECRET_TEST}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES:-20}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS:-30}
      JWT_REFRESH_GRACE_SECONDS: ${JWT_REFRESH_GRACE_SECONDS:-10}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS_TEST}
      SYSACAD_ENABLED: ${SYSACAD_ENABLED}
      SYSACAD_API_KEY: ${SYSACAD_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    external: true
