spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000

cors:
  allowed-origins:
    - http://localhost:5173

logging:
  level:
    root: ERROR
    ar.edu.utn.frc.classroom_allocation: WARN
