-- =============================================================================
-- 001_envers_tablas_auditoria.sql
-- =============================================================================
--
-- Qué es:
--   Tablas de auditoría de Hibernate Envers para el módulo `allocation` (ver
--   ADR-007-auditoria-envers-en-allocation.md): la tabla de revisiones
--   `revinfo` y una tabla `*_aud` por cada entidad auditada
--   (`Allocation`, `Occurrence`, `AcademicEvent` + sus subtipos JOINED
--   `RecurringEvent`/`UniqueEvent`), que registran el estado de cada fila en
--   cada revisión (INSERT/UPDATE/DELETE) que la tocó.
--
-- Por qué:
--   Fase 5 del refactor agrega `org.hibernate.orm:hibernate-envers` y marca
--   `@Audited` las 5 entidades de `allocation` para poder responder "quién y
--   cuándo" creó, modificó o eliminó una asignación de aula, ocurrencia o
--   evento académico. Como el esquema de SIGA no usa Flyway/Liquibase (ver
--   `docs/ddl/README.md`), estas tablas se crean a mano antes de desplegar la
--   versión que las requiere.
--
-- Debe aplicarse antes de deployar esta versión:
--   La app corre con `ddl-auto: validate`, así que **no levanta** si estas
--   tablas no existen y las entidades auditadas quedan mapeadas. Aplicar este
--   script en la base de datos compartida ANTES de desplegar la versión que
--   incluye la Fase 5 del refactor.
--
-- Origen / cómo se verificó:
--   El script se generó levantando la app con el perfil `dev-local`
--   (`ddl-auto: create-drop`, Postgres efímero por Docker Compose) y
--   volcando el esquema resultante con `pg_dump --schema-only`, filtrado a
--   `revinfo` y las 5 tablas `*_aud`. Es exactamente lo que Hibernate/Envers
--   generan a partir del mapeo de las entidades de `allocation` con la
--   versión de Hibernate ORM 7 que usa el proyecto — no es una derivación a
--   mano. En particular, se verificó así (en vez de asumirlo) que Envers
--   agrega la columna `revtype` en `evento_academico_aud` (tabla raíz de la
--   herencia JOINED) pero NO la repite en las tablas de las subclases
--   `evento_recurrente_aud` / `evento_unico_academico_aud` — el estado de esa
--   fila en la revisión ya se conoce por la fila correspondiente en
--   `evento_academico_aud`, que comparte (rev, id_evento_academico).
--
-- No se genera tabla de auditoría para `evento_recurrente_fecha_excluida`
-- (colección `RecurringEvent.excludedDates`): el campo está marcado
-- `@NotAudited` porque es un campo obsoleto que ningún flujo actual escribe
-- (ver ADR-007 y `plan-refactor.md`, punto D5).
--
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabla de revisiones (una fila por transacción que tocó alguna entidad
-- @Audited). `SigaRevision` (common/audit) es la entidad de revisión propia:
-- reemplaza el timestamp `long` por defecto de Envers por un
-- `LocalDateTime` legible directamente.
-- -----------------------------------------------------------------------------
CREATE TABLE public.revinfo (
    rev             integer NOT NULL,
    fecha_revision  timestamp(6) without time zone NOT NULL,
    CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
);

ALTER TABLE public.revinfo
    ALTER COLUMN rev ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.revinfo_rev_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- -----------------------------------------------------------------------------
-- asignacion_aula_aud — auditoría de Allocation
-- -----------------------------------------------------------------------------
CREATE TABLE public.asignacion_aula_aud (
    id_asignacion   bigint NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint,
    id_ocurrencia   bigint,
    id_aula         integer,
    origen          character varying(255),
    fecha_creacion  timestamp(6) without time zone,
    observaciones   character varying(255),
    CONSTRAINT asignacion_aula_aud_pkey PRIMARY KEY (rev, id_asignacion),
    CONSTRAINT asignacion_aula_aud_origen_check
        CHECK (((origen)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTOMATIC'::character varying, 'IMPORTED'::character varying])::text[]))),
    CONSTRAINT fkfjl2akgh9d7j8r9cgoteku442
        FOREIGN KEY (rev) REFERENCES public.revinfo(rev)
);

-- -----------------------------------------------------------------------------
-- ocurrencia_aud — auditoría de Occurrence
-- -----------------------------------------------------------------------------
CREATE TABLE public.ocurrencia_aud (
    id_ocurrencia         bigint NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint,
    id_evento_academico   bigint,
    fecha                 date,
    estado                character varying(255),
    CONSTRAINT ocurrencia_aud_pkey PRIMARY KEY (rev, id_ocurrencia),
    CONSTRAINT ocurrencia_aud_estado_check
        CHECK (((estado)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'ASSIGNED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT fk70p3nmfm1jhnow6dhxrshvvde
        FOREIGN KEY (rev) REFERENCES public.revinfo(rev)
);

-- -----------------------------------------------------------------------------
-- evento_academico_aud — auditoría de AcademicEvent (raíz de la herencia
-- JOINED; columnas comunes a RecurringEvent y UniqueEvent)
-- -----------------------------------------------------------------------------
CREATE TABLE public.evento_academico_aud (
    id_evento_academico   bigint NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint,
    tipo_evento           character varying(31) NOT NULL,
    cantidad_inscriptos   integer,
    hora_inicio           time(0) without time zone,
    duracion_minutos      integer,
    CONSTRAINT evento_academico_aud_pkey PRIMARY KEY (rev, id_evento_academico),
    CONSTRAINT fk79v89sx1qsacrl9yjir1xp1mi
        FOREIGN KEY (rev) REFERENCES public.revinfo(rev)
);

-- -----------------------------------------------------------------------------
-- evento_recurrente_aud — auditoría de RecurringEvent (subclase JOINED).
-- Sin columna `revtype` propia: el tipo de revisión de esta fila ya lo da
-- evento_academico_aud para el mismo (rev, id_evento_academico).
-- -----------------------------------------------------------------------------
CREATE TABLE public.evento_recurrente_aud (
    id_evento_academico   bigint NOT NULL,
    rev                   integer NOT NULL,
    dia_semana            character varying(255),
    fecha_inicio          date,
    fecha_fin             date,
    id_materia            bigint,
    id_comision           bigint,
    CONSTRAINT evento_recurrente_aud_pkey PRIMARY KEY (rev, id_evento_academico),
    CONSTRAINT evento_recurrente_aud_dia_semana_check
        CHECK (((dia_semana)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))),
    CONSTRAINT fkqm8ifi0mtsqh908xxtc2u32jv
        FOREIGN KEY (rev, id_evento_academico) REFERENCES public.evento_academico_aud(rev, id_evento_academico)
);

-- -----------------------------------------------------------------------------
-- evento_unico_academico_aud — auditoría de UniqueEvent (subclase JOINED).
-- Sin columna `revtype` propia, misma razón que evento_recurrente_aud.
-- -----------------------------------------------------------------------------
CREATE TABLE public.evento_unico_academico_aud (
    id_evento_academico   bigint NOT NULL,
    rev                   integer NOT NULL,
    fecha                 date,
    descripcion           character varying(255),
    CONSTRAINT evento_unico_academico_aud_pkey PRIMARY KEY (rev, id_evento_academico),
    CONSTRAINT fkg9mo5p6qgfr5cv2rrh1u8bt88
        FOREIGN KEY (rev, id_evento_academico) REFERENCES public.evento_academico_aud(rev, id_evento_academico)
);
