CREATE TABLE notificacion (
    id_notificacion     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantilla           varchar(60)  NOT NULL,
    canal               varchar(30)  NOT NULL,
    destinatario        varchar(150) NOT NULL,
    destinatario_nombre varchar(150),
    asunto              varchar(255) NOT NULL,
    cuerpo              text         NOT NULL,
    estado              varchar(20)  NOT NULL,
    intentos            int          NOT NULL DEFAULT 0,
    proximo_intento     timestamp,
    ultimo_error        varchar(500),
    clave_idempotencia  varchar(120) NOT NULL,
    solicitado_por      varchar(150),
    fecha_envio         timestamp,
    creado_en           timestamp    NOT NULL,
    actualizado_en      timestamp    NOT NULL,
    CONSTRAINT uq_notificacion_idempotencia UNIQUE (clave_idempotencia, canal, destinatario)
);

CREATE INDEX idx_notificacion_pendientes ON notificacion (estado, proximo_intento);
