-- Archive of old audit rows: schema "archivo" mirrors four tables of public (revinfo, revinfo_resumen,
-- ocurrencia_aud, asignacion_aula_aud). AuditArchiveRepository copies rows there with SELECT a.* (positional),
-- so any future ALTER on one of those four public tables must repeat the ALTER on archivo.<table>.
-- Guide (Spanish): .claude/docs/audit/archivo-auditoria.md
--
-- LIKE ... INCLUDING INDEXES copies primary keys (needed by ON CONFLICT DO NOTHING) and the lookup indexes.
-- It never copies foreign keys: the archive does not depend on public.revinfo. CHECK constraints are left out
-- on purpose: a value added later to an active enum would make the batch fail forever. NOT NULL is always copied.
-- No INCLUDING IDENTITY: archivo.revinfo.rev is a plain integer that keeps the original revision number.
CREATE SCHEMA IF NOT EXISTS archivo;

CREATE TABLE archivo.revinfo             (LIKE public.revinfo             INCLUDING INDEXES);
CREATE TABLE archivo.revinfo_resumen     (LIKE public.revinfo_resumen     INCLUDING INDEXES);
CREATE TABLE archivo.ocurrencia_aud      (LIKE public.ocurrencia_aud      INCLUDING INDEXES);
CREATE TABLE archivo.asignacion_aula_aud (LIKE public.asignacion_aula_aud INCLUDING INDEXES);

-- One row per archive run that moved rows, audited by Envers (entity AuditArchiveRun).
CREATE TABLE archivado_auditoria (
    id_archivado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_ejecucion timestamp(6) NOT NULL,
    ciclo_conservado_desde integer NOT NULL,
    fecha_corte date NOT NULL,
    estado varchar(30) NOT NULL,
    filas_ocurrencia bigint NOT NULL,
    filas_asignacion bigint NOT NULL,
    revisiones_borradas bigint NOT NULL,
    mensaje_error varchar(255)
);

CREATE TABLE archivado_auditoria_aud (
    id_archivado bigint NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    fecha_ejecucion timestamp(6),
    ciclo_conservado_desde integer,
    fecha_corte date,
    estado varchar(30),
    filas_ocurrencia bigint,
    filas_asignacion bigint,
    revisiones_borradas bigint,
    mensaje_error varchar(255),
    PRIMARY KEY (id_archivado, rev)
);
CREATE INDEX idx_archivado_auditoria_aud_rev ON archivado_auditoria_aud (rev);

-- Privileges. V1 has no GRANT because roles change per environment, and the app role differs from the
-- Flyway one. Every role (not PUBLIC, not the owner) that holds privileges on public.ocurrencia_aud gets
-- the same privileges on the archive tables and on the two new tables, plus USAGE on the schema.
-- Roles come from pg_class.relacl joined to pg_roles, so a grantee that does not exist is skipped.
-- With a null relacl (owner-only table, e.g. in Testcontainers) the loop does not run.
DO $$
DECLARE
    r record;
    t text;
BEGIN
    FOR r IN
        SELECT g.rolname, string_agg(DISTINCT a.privilege_type, ', ' ORDER BY a.privilege_type) AS privileges
          FROM pg_class c
         CROSS JOIN LATERAL aclexplode(c.relacl) a
          JOIN pg_roles g ON g.oid = a.grantee
         WHERE c.oid = 'public.ocurrencia_aud'::regclass
           AND a.grantee <> c.relowner
         GROUP BY g.rolname
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA archivo TO %I', r.rolname);
        -- Tables created later in the schema by the migration role (e.g. a future ALTER-by-recreate) inherit the same grants.
        EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA archivo GRANT %s ON TABLES TO %I',
                       current_user, r.privileges, r.rolname);
        FOREACH t IN ARRAY ARRAY['archivo.revinfo', 'archivo.revinfo_resumen', 'archivo.ocurrencia_aud',
                                 'archivo.asignacion_aula_aud', 'public.archivado_auditoria',
                                 'public.archivado_auditoria_aud']
        LOOP
            EXECUTE format('GRANT %s ON %s TO %I', r.privileges, t, r.rolname);
        END LOOP;
    END LOOP;
END
$$;
