-- RBAC con alcance por edificio (Plan maestro §4). Los roles NO viven en BD: son el enum
-- SystemRole en código. Esta migración agrega nombre/apellido al usuario y reescribe
-- usuario_rol como tabla de asignaciones (rol + tipo_alcance + id_alcance).
-- Numeración V3 según el plan maestro (V4 = auditoría, V5 = periodo académico);
-- Flyway no exige numeración contigua.
-- Nombres de constraint verificados contra V1__baseline_schema.sql.

-- --- usuario: nombre y apellido -------------------------------------------------
ALTER TABLE usuario ADD COLUMN nombre   varchar(100);
ALTER TABLE usuario ADD COLUMN apellido varchar(100);

-- Backfill de las filas previas al alta de la columna (placeholder; el equipo puede
-- corregirlo por operación si decide derivarlo del correo).
UPDATE usuario SET nombre   = '-' WHERE nombre   IS NULL;
UPDATE usuario SET apellido = '-' WHERE apellido IS NULL;

ALTER TABLE usuario ALTER COLUMN nombre   SET NOT NULL;
ALTER TABLE usuario ALTER COLUMN apellido SET NOT NULL;

ALTER TABLE usuario_aud ADD COLUMN nombre   varchar(100);
ALTER TABLE usuario_aud ADD COLUMN apellido varchar(100);

-- --- usuario_rol: de colección de roles a tabla de asignaciones ---------------
ALTER TABLE usuario_rol DROP CONSTRAINT chk_usuario_rol_valor;
ALTER TABLE usuario_rol DROP CONSTRAINT uq_usuario_rol;

ALTER TABLE usuario_rol ADD COLUMN id_usuario_rol bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE usuario_rol ADD PRIMARY KEY (id_usuario_rol);

ALTER TABLE usuario_rol ALTER COLUMN rol TYPE varchar(50);

ALTER TABLE usuario_rol ADD COLUMN tipo_alcance varchar(20);
UPDATE usuario_rol SET tipo_alcance = 'GLOBAL' WHERE tipo_alcance IS NULL;
ALTER TABLE usuario_rol ALTER COLUMN tipo_alcance SET NOT NULL;

ALTER TABLE usuario_rol ADD COLUMN id_alcance bigint;

ALTER TABLE usuario_rol ADD CONSTRAINT uq_usuario_rol
    UNIQUE (id_usuario, rol, tipo_alcance, id_alcance);

-- En Postgres NULL <> NULL dentro de un UNIQUE, así que la constraint de arriba no
-- atrapa duplicados de un rol GLOBAL (id_alcance NULL). El índice parcial cierra eso.
CREATE UNIQUE INDEX uq_usuario_rol_global
    ON usuario_rol (id_usuario, rol) WHERE id_alcance IS NULL;

-- --- usuario_rol_aud: PK subrogada para Envers -------------------------------
ALTER TABLE usuario_rol_aud DROP CONSTRAINT usuario_rol_aud_rol_check;
ALTER TABLE usuario_rol_aud DROP CONSTRAINT pk_usuario_rol_aud;

ALTER TABLE usuario_rol_aud ADD COLUMN id_usuario_rol bigint;
ALTER TABLE usuario_rol_aud ADD COLUMN tipo_alcance   varchar(20);
ALTER TABLE usuario_rol_aud ADD COLUMN id_alcance     bigint;
ALTER TABLE usuario_rol_aud ALTER COLUMN rol TYPE varchar(50);

-- El id subrogado del histórico viejo no se puede reconstruir: se descarta y la PK
-- nueva arranca desde las revisiones nuevas.
DELETE FROM usuario_rol_aud WHERE id_usuario_rol IS NULL;
ALTER TABLE usuario_rol_aud ADD CONSTRAINT pk_usuario_rol_aud PRIMARY KEY (id_usuario_rol, rev);
