-- Schema para resolver pedidos de aula: asignar, notificar, derivar, devolver y cancelar.
-- Numeración V6: siguiente libre tras V1-V5 existentes.

ALTER TABLE solicitud_aula_item ADD COLUMN IF NOT EXISTS id_edificio_derivado bigint;
ALTER TABLE solicitud_aula_item ADD COLUMN IF NOT EXISTS fecha_derivacion timestamp without time zone;
ALTER TABLE solicitud_aula_item ADD COLUMN IF NOT EXISTS id_edificio_devuelto bigint;
ALTER TABLE solicitud_aula_item ADD COLUMN IF NOT EXISTS motivo_devolucion character varying(255);
ALTER TABLE solicitud_aula_item ADD COLUMN IF NOT EXISTS fecha_notificacion timestamp without time zone;

ALTER TABLE solicitud_aula_item_aud ADD COLUMN IF NOT EXISTS id_edificio_derivado bigint;
ALTER TABLE solicitud_aula_item_aud ADD COLUMN IF NOT EXISTS fecha_derivacion timestamp without time zone;
ALTER TABLE solicitud_aula_item_aud ADD COLUMN IF NOT EXISTS id_edificio_devuelto bigint;
ALTER TABLE solicitud_aula_item_aud ADD COLUMN IF NOT EXISTS motivo_devolucion character varying(255);
ALTER TABLE solicitud_aula_item_aud ADD COLUMN IF NOT EXISTS fecha_notificacion timestamp without time zone;

ALTER TABLE solicitud_aula_item DROP CONSTRAINT IF EXISTS chk_solicitud_item_estado;
ALTER TABLE solicitud_aula_item ADD CONSTRAINT chk_solicitud_item_estado
    CHECK (estado = ANY (ARRAY['PENDING', 'DERIVED_TO_BUILDING', 'PRE_APPROVED', 'RESOLVED', 'CANCELLED']));

ALTER TABLE solicitud_aula_item_aud DROP CONSTRAINT IF EXISTS solicitud_aula_item_aud_estado_check;
ALTER TABLE solicitud_aula_item_aud ADD CONSTRAINT solicitud_aula_item_aud_estado_check
    CHECK (estado = ANY (ARRAY['PENDING', 'DERIVED_TO_BUILDING', 'PRE_APPROVED', 'RESOLVED', 'CANCELLED']));

CREATE TABLE IF NOT EXISTS solicitud_item_asignacion (
    id_item_asignacion bigint GENERATED BY DEFAULT AS IDENTITY,
    id_item bigint NOT NULL,
    id_ocurrencia bigint NOT NULL,
    id_aula bigint NOT NULL,
    orden integer NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_solicitud_item_asignacion PRIMARY KEY (id_item_asignacion),
    CONSTRAINT chk_solicitud_item_asignacion_orden CHECK (orden >= 1),
    CONSTRAINT uq_solicitud_item_asignacion_item_ocurrencia UNIQUE (id_item, id_ocurrencia),
    CONSTRAINT fk_solicitud_item_asignacion_item FOREIGN KEY (id_item) REFERENCES solicitud_aula_item(id_item),
    CONSTRAINT fk_solicitud_item_asignacion_ocurrencia FOREIGN KEY (id_ocurrencia) REFERENCES ocurrencia(id_ocurrencia),
    CONSTRAINT fk_solicitud_item_asignacion_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

CREATE INDEX IF NOT EXISTS idx_solicitud_item_asignacion_item ON solicitud_item_asignacion (id_item);

CREATE TABLE IF NOT EXISTS solicitud_item_asignacion_aud (
    id_item_asignacion bigint NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    id_item bigint,
    id_ocurrencia bigint,
    id_aula bigint,
    orden integer,
    CONSTRAINT pk_solicitud_item_asignacion_aud PRIMARY KEY (id_item_asignacion, rev),
    CONSTRAINT fk_solicitud_item_asignacion_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

ALTER TABLE ocurrencia ADD COLUMN IF NOT EXISTS orden_aula integer DEFAULT 1 NOT NULL;
ALTER TABLE ocurrencia ADD COLUMN IF NOT EXISTS id_ocurrencia_principal bigint;

ALTER TABLE ocurrencia_aud ADD COLUMN IF NOT EXISTS orden_aula integer;
ALTER TABLE ocurrencia_aud ADD COLUMN IF NOT EXISTS id_ocurrencia_principal bigint;

ALTER TABLE ocurrencia DROP CONSTRAINT IF EXISTS uq_ocurrencia_evento_fecha;
ALTER TABLE ocurrencia ADD CONSTRAINT uq_ocurrencia_evento_fecha_slot
    UNIQUE (id_evento_academico, fecha, orden_aula);
CREATE INDEX IF NOT EXISTS idx_ocurrencia_evento_fecha ON ocurrencia (id_evento_academico, fecha);

CREATE TABLE IF NOT EXISTS notificacion_saliente (
    id_notificacion bigint GENERATED BY DEFAULT AS IDENTITY,
    destinatario character varying(255) NOT NULL,
    canal character varying(50) NOT NULL,
    payload text NOT NULL,
    estado character varying(30) DEFAULT 'PENDING' NOT NULL,
    intentos integer DEFAULT 0 NOT NULL,
    error character varying(500),
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notificacion_saliente PRIMARY KEY (id_notificacion)
);
